include(
        ":retrograde-util",
        ":retrograde-app-shared",
        ":lemuroid-touchinput",
        ":lemuroid-app",
        ":lemuroid-metadata-libretro-db",
        ":lemuroid_core_gambatte",
        ":lemuroid_core_desmume",
        ":lemuroid_core_fbneo",
        ":lemuroid_core_fceumm",
        ":lemuroid_core_genesis_plus_gx",
        ":lemuroid_core_mgba",
        ":lemuroid_core_mupen64plus_next_gles3",
        ":lemuroid_core_pcsx_rearmed",
        ":lemuroid_core_ppsspp",
        ":lemuroid_core_snes9x",
        ":lemuroid_core_stella"
)
