package com.swordfish.lemuroid.app.mobile.shared.compose.ui

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006E24)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6AFF86)
val md_theme_light_onPrimaryContainer = Color(0xFF002105)
val md_theme_light_secondary = Color(0xFF3F734C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBBFCC4)
val md_theme_light_onSecondaryContainer = Color(0xFF012C11)
val md_theme_light_tertiary = Color(0xFF0D9768)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB1FFE5)
val md_theme_light_onTertiaryContainer = Color(0xFF002316)
val md_theme_light_error = Color(0xFFD40000)
val md_theme_light_errorContainer = Color(0xFFFFDAD4)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410000)
val md_theme_light_background = Color(0xFFFDFFF5)
val md_theme_light_onBackground = Color(0xFF182014)
val md_theme_light_surface = Color(0xFFFDFFF5)
val md_theme_light_onSurface = Color(0xFF182014)
val md_theme_light_surfaceVariant = Color(0xFFDBF2CB)
val md_theme_light_onSurfaceVariant = Color(0xFF3C5334)
val md_theme_light_outline = Color(0xFF717B6C)
val md_theme_light_inverseOnSurface = Color(0xFFF4F7E4)
val md_theme_light_inverseSurface = Color(0xFF2A3726)
val md_theme_light_inversePrimary = Color(0xFF20FF57)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E24)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF20FF57)
val md_theme_dark_onPrimary = Color(0xFF00390E)
val md_theme_dark_primaryContainer = Color(0xFF005319)
val md_theme_dark_onPrimaryContainer = Color(0xFF6AFF86)
val md_theme_dark_secondary = Color(0xFFA1DFA9)
val md_theme_dark_onSecondary = Color(0xFF164123)
val md_theme_dark_secondaryContainer = Color(0xFF295A35)
val md_theme_dark_onSecondaryContainer = Color(0xFFBBFCC4)
val md_theme_dark_tertiary = Color(0xFF76FFCF)
val md_theme_dark_onTertiary = Color(0xFF003C25)
val md_theme_dark_tertiaryContainer = Color(0xFF007248)
val md_theme_dark_onTertiaryContainer = Color(0xFFB1FFE5)
val md_theme_dark_error = Color(0xFFFFB3A8)
val md_theme_dark_errorContainer = Color(0xFF930005)
val md_theme_dark_onError = Color(0xFF680002)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD4)
val md_theme_dark_background = Color(0xFF182014)
val md_theme_dark_onBackground = Color(0xFFE7EAD5)
val md_theme_dark_surface = Color(0xFF182014)
val md_theme_dark_onSurface = Color(0xFFE7EAD5)
val md_theme_dark_surfaceVariant = Color(0xFF3C5334)
val md_theme_dark_onSurfaceVariant = Color(0xFFBBD8AD)
val md_theme_dark_outline = Color(0xFF899585)
val md_theme_dark_inverseOnSurface = Color(0xFF182014)
val md_theme_dark_inverseSurface = Color(0xFFE7EAD5)
val md_theme_dark_inversePrimary = Color(0xFF006E24)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDDDDDD)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF00C64E)
